---
# tasks file for installing mongodb on debian

- name: update apt cache
  shell: "apt update"

- name: install mongodb package
  apt:
    name: mongodb
    state: present

- name: Remove mongod default file
  file:
    path: /etc/mongod.conf
    state: absent

- name: Copy the mongod conf
  template:
    src: mongod-debian.j2
    dest: /etc/mongod.conf

- name: create data/db directory
  file: 
    path: /data/db
    state: directory
    owner: "{{ ansible_user }}"

- name: run the mongodb in background
  shell: "mongod --fork --syslog"
  